-- CREATE TABLE IF NOT EXISTS user_roles (
--     id SERIAL PRIMARY KEY,
--     role_name VARCHAR(20) NOT NULL);
--
-- INSERT INTO user_roles (role_name) VALUES ('ADMIN'), ('WASTE_COLLECTOR'), ('RESIDENT'), ('COMPANY');

CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(11) NOT NULL,
    role VARCHAR(255) NOT NULL,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

